### ISSUE TITLE
huawei Nexus 6p issue? version1.1.8

### ISSUE THREAD

**Issue by Erichkko** [leolin310148/ShortcutBadger#105]
` Unable to execute badge
                                                                 me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
                                                                     at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:77)
                                                                     at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:52)
                                                                     at com.ncs.msg.utils.BadgeNumberUtil.showBadgeNumber(BadgeNumberUtil.java:25)
                                                                     at com.ncs.msg.ui.activity.MainActivity$8.onPostExecute(MainActivity.java:483)`

**Comment by Holstie** [comment]
Nexus is a google phone so it's not possible to create a badge

**Comment by mlabarca** [comment]
Note that badge support comes from the launcher, so technically it's possible to get badges working on a google device. I have a Moto X Play using Nova Launcher + teslaunread and I have badges working, for example. However I think most users won't change their phone's launcher like I did, so you can still consider those devices as unsupported as @Holstie points out.

**Comment by Erichkko** [comment]
Yes i know,nexus unsupported ,but when i debug that display error log ,we can fix it?

**Comment by steelbytes** [comment]
@Erichkko you can call applyCountOrThrow instead of applyCount and catch ShortcutBadgeException and ignore it
