### ISSUE TITLE
Unable to set Badge when application is in Background

### ISSUE THREAD

**Issue by neurospeech** [leolin310148/ShortcutBadger#107]
I have GCM push notification setup, in the receiver, I am trying to set Badge, I was using 1.1.3 which was working fine until Android 5.1. Now I am getting error,

```
Handler (me.leolin.shortcutbadger.impl.SonyHomeBadger$1) {9dbaf3a} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (me.leolin.shortcutbadger.impl.SonyHomeBadger$1) {9dbaf3a} sending message to a Handler on a dead thread
    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:600)
    at android.os.Handler.enqueueMessage(Handler.java:631)
    at android.os.Handler.sendMessageAtTime(Handler.java:600)
    at android.os.Handler.sendMessageDelayed(Handler.java:570)
    at android.os.Handler.sendMessage(Handler.java:507)
    at android.os.Message.sendToTarget(Message.java:416)
    at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:120)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:224)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

When application is in background,  Application's main looper is not running, so enqueueMessage fails. I think most of other people are having same issue.

**Comment by leolin310148** [comment]
Maybe you can try to send an intent to service and handle the badge inside the service.

**Comment by webmaster128** [comment]
@neurospeech could you solve the problem? Is it necessary to call `ShortcutBadger.applyCount` from the main thread or can you use a worker thread directly?
