### ISSUE TITLE
Crashing Samsung Galaxy S7 Edge

### ISSUE THREAD

**Issue by pedronveloso** [leolin310148/ShortcutBadger#110]
Trying to set a badge will crash for `Samsung SM-G935T` running Android 6.0.1. Confirmed in multiple devices.

`Fatal Exception: java.lang.SecurityException: Missing permission to insert badges
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
       at android.content.ContentResolver.insert(ContentResolver.java:1284)
       at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by leolin310148** [comment]
Hi, Can you tell me which version of shortcutbadger you are using?

**Comment by pedronveloso** [comment]
Version `1.1.8`

**Comment by KaNcHeR** [comment]
API >= 23 now require special permission. Try to make it through `onRequestPermissionsResult`

**Comment by Farbklex** [comment]
What permission is required? I am using it on the S7 with Android 6 and API 23 and it works great so far..

**Comment by Srain-z** [comment]
I am using it on the S7 with Android 6.0.1 and API 23 and it can't works.Toast show is success but on the luncher haven't badge.

**Comment by jimmychou927** [comment]
it's working well after 
insert
`
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
`
`
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
`
and 
`
<uses-permission android:name="com.sec.android.provider.badge.BadgeProvider" />  
`
to AndroidManifest.xml

**Comment by leolin310148** [comment]
Samsung should handle well in 1.1.12.
