### ISSUE TITLE
Cannot use in MIUI6?

### ISSUE THREAD

**Issue by joshuatam** [leolin310148/ShortcutBadger#112]
Very interesting problem found, I call this code inside the fragment but no badge displayed

```
ShortcutBadger.applyCount(getActivity(), totalCount);
```

Log:

```
Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }
                                                                             at me.leolin.shortcutbadger.impl.XiaomiHomeBadger.executeBadge(XiaomiHomeBadger.java:41)
                                                                             at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:75)
                                                                             at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:52) 
```

While it will display badge (number = 1) when using normal Notification.

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
