### ISSUE TITLE
miui7 is cannot set shorBadger

### ISSUE THREAD

**Issue by lileini** [leolin310148/ShortcutBadger#113]
Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }
                                                                                           at me.leolin.shortcutbadger.impl.XiaomiHomeBadger.executeBadge(XiaomiHomeBadger.java:41)
                                                                                           at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:75)
                                                                                           at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:52) 
                                                                                           at com.example.administrator.shortbadger.MainActivity$1.onClick(MainActivity.java:56)

**Comment by sirius007** [comment]
I have the same issues!    any idea?

**Comment by leoleohan** [comment]
MIUI 6+, go to [http://dev.xiaomi.com/doc/p=3904/index.html](http://dev.xiaomi.com/doc/p=3904/index.html)

**Comment by leolin310148** [comment]
trying to add more support for Xiaomi in 1.1.12, please wait the new version available and help to test, thanks!
