### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by cfs5403** [leolin310148/ShortcutBadger#164]
Hit null pointer exception on Samsung SM-N910G device, android 6.0.1

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
       at me.leolin.shortcutbadger.ShortcutBadger.initBadger(ShortcutBadger.java:117)
       at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:82)
       at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:64)
       at com.mhcasia.android.fragment.HomeFragment$8.onComplete(HomeFragment.java:412)
       at com.mhcasia.android.model.MHCMessageCollection$1.onResponse(MHCMessageCollection.java:86)
       at com.mhcasia.android.model.MHCMessageCollection$1.onResponse(MHCMessageCollection.java:60)
       at com.mhcasia.android.utility.MHCRequest.deliverResponse(MHCRequest.java:87)
       at com.mhcasia.android.utility.MHCRequest.deliverResponse(MHCRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by cfs5403** [comment]
Problem solve, is my app fault. The getActivity at fragment sometimes return null so causing the app crash.

`ShortcutBadger.applyCount(getActivity(), count);`
