### ISSUE TITLE
Not working on Oppo and Vivo :

### ISSUE THREAD

**Issue by sujayun** [leolin310148/ShortcutBadger#243]
1) Not working on Vivo V5 Plus and displays no log.

2) Not working on oppo A37 mobile, I am getting the following log :

11-14 14:27:58.513 16708-16758/ D/FA: Application backgrounded. Logging engagement
11-14 14:27:58.513 16708-16758/ D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=3550}]
11-14 14:27:58.513 16708-16758/ D/FA: Connected to remote service
11-14 14:27:58.523 16708-16758/ E/FA: Task exception on worker thread: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/-1/base.apk): com.google.android.gms.measurement.internal.zzt.zzEd(Unknown Source)
11-14 14:28:03.523 16708-16758/ W/ContextImpl: forgetServiceDispatcher failed for:
                                                              java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzad$zza@8c2c8a8
                                                                  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1105)
                                                                  at android.app.ContextImpl.unbindService(ContextImpl.java:1872)
                                                                  at android.content.ContextWrapper.unbindService(ContextWrapper.java:562)
                                                                  at com.google.android.gms.common.stats.zzb.zza(Unknown Source)
                                                                  at com.google.android.gms.measurement.internal.zzad.disconnect(Unknown Source)
                                                                  at com.google.android.gms.measurement.internal.zzad.zzmo(Unknown Source)
                                                                  at com.google.android.gms.measurement.internal.zzad.zzb(Unknown Source)
                                                                  at com.google.android.gms.measurement.internal.zzad$1.run(Unknown Source)
                                                                  at com.google.android.gms.measurement.internal.zzf$1.run(Unknown Source)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at com.google.android.gms.measurement.internal.zzw$zzd.run(Unknown Source)

**Comment by jiangfei891111** [comment]
not working  too , how to resolve this ?

**Comment by julia40124009** [comment]
Oppo r9s work fine

**Comment by pallaviwaghaye** [comment]
not working for me also,how to resolve this issue...if anyone have idea please share..
thank you
