### ISSUE TITLE
java.lang.SecurityException: Missing permission to insert badges

### ISSUE THREAD

**Issue by sidhiartha** [leolin310148/ShortcutBadger#256]
Device: Xiaomi Redmi 3S
OS: 7.1.2 (it can be Android 7.1.2 or MiUI 7.1.2, crashlytics only show OS as 7.1.2)

Thanks in advanced

**Comment by maverick-2013** [comment]
Same issue on LG G5, Android 7.0

**Comment by daydreary** [comment]
Same issue on Sony device. Here is the log:

406-06 09:40:51.265 16752 32059 E AndroidRuntime: FATAL EXCEPTION: AsyncQueryWorker
--
506-06 09:40:51.265 16752 32059 E AndroidRuntime: Process: com.sohu.sohuhy, PID: 16752
606-06 09:40:51.265 16752 32059 E AndroidRuntime: java.lang.SecurityException: Missing permission to insert badges
706-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1959)
806-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
906-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
1006-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
1106-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.content.ContentResolver.insert(ContentResolver.java:1542)
1206-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
1306-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105)
1406-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.os.Looper.loop(Looper.java:251)
1506-06 09:40:51.265 16752 32059 E AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:65)
