### ISSUE TITLE
S6 Edge latest OS version causing a SQL crash

### ISSUE THREAD

**Issue by N2Android** [leolin310148/ShortcutBadger#31]
Hi,

We have been using your ShortcutBadge for a couple of months but have noticed that since the last OS update 5.1.1 - Build - LMY47X.G92FXXU2BOGB on the S6 Edge the badge stopped working and the following crash is occurring every time we attempt to update the badge,

 E/DatabaseUtils﹕ Writing exception to parcel
    android.database.sqlite.SQLiteException: no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?)
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?))
    #################################################################
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
            at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
            at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
            at com.sec.android.provider.badge.BadgeProvider.query(BadgeProvider.java:153)
            at android.content.ContentProvider.query(ContentProvider.java:1007)
            at android.content.ContentProvider$Transport.query(ContentProvider.java:218)
            at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
            at android.os.Binder.execTransact(Binder.java:461)
07-30 15:09:54.133  23203-25032/com.*.* E/ShortcutBadger﹕ no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?)
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?))
    #################################################################
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?)
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?))
    #################################################################)
    #################################################################
    android.database.sqlite.SQLiteException: no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?)
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?))
    #################################################################
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?)
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    (no such column: _id (code 1): , while compiling: SELECT _id, class FROM apps WHERE (package=?))
    #################################################################)
    #################################################################
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
            at android.content.ContentResolver.query(ContentResolver.java:489)
            at android.content.ContentResolver.query(ContentResolver.java:433)
            at me.leolin.shortcutbadger.impl.SamsungHomeBadger.executeBadge(SamsungHomeBadger.java:32)
            at me.leolin.shortcutbadger.ShortcutBadger.count(ShortcutBadger.java:118)

Thanks you for the cool lib, we would like to continue using it.

**Comment by leolin310148** [comment]
Please try 1.1.3. 
In 1.1.3, Samsung devices will use DefaultBadger to send broadcast to Launcher for showing badge.
(Tested on my Samsung phone with 4.2.2)

**Comment by N2Android** [comment]
Thank you very much.

That solved our problems on the S6.

Strangely we did not have problems on other devices.
