### ISSUE TITLE
Crash on android preview L emulator

### ISSUE THREAD

**Issue by elikonky-houzz** [leolin310148/ShortcutBadger#5]
Hi

Tried it on preview (L) emulator. Got this. 

java.lang.SecurityException: Permission Denial: writing com.android.launcher2.LauncherProvider uri content://com.android.launcher2.settings/favorites?notify=true from pid=3128, uid=10056 requires com.android.launcher.permission.WRITE_SETTINGS, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1489)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
at android.content.ContentProviderProxy.update(ContentProviderNative.java:567)
at android.content.ContentResolver.update(ContentResolver.java:1321)
at com.shortcutBadger.impl.AndroidHomeBadger.executeBadge(AndroidHomeBadger.java:37)
at com.shortcutBadger.ShortcutBadger.setBadge(ShortcutBadger.java:74)

**Comment by leolin310148** [comment]
cannot support  com.android.launcher3

**Comment by Liwenfu** [comment]
did you solved it?
