### ISSUE TITLE
NPE on ShortcutBadger.initBadger

### ISSUE THREAD

**Issue by sideprojecteu** [leolin310148/ShortcutBadger#66]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
    at me.leolin.shortcutbadger.ShortcutBadger.initBadger(ShortcutBadger.java:92)
    at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:65)
    at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:50)

on HUAWEI HUAWEI GRA-L09 Android 5.0.1

**Comment by opayen** [comment]
I fixed this issue here: https://github.com/leolin310148/ShortcutBadger/pull/72
