### ISSUE TITLE
java.lang.NoSuchMethodException: <init> [class android.content.Context]

### ISSUE THREAD

**Issue by Malachiasz** [leolin310148/ShortcutBadger#70]
There is something wrong in this code:

```
            for (Class<? extends ShortcutBadger> badger : BADGERS) {
                Constructor<? extends ShortcutBadger> constructor = badger.getConstructor(Context.class);
                ShortcutBadger shortcutBadger = constructor.newInstance(context);
                if (shortcutBadger.getSupportLaunchers().contains(currentHomePackage)) {
                    mShortcutBadger = shortcutBadger;
                    break;
                }
            }
        } catch (Exception e) {
            Log.e(LOG_TAG, e.getMessage(), e);
        }
```

As it's printing this error log all the time. Please if it's expected behavior stop polluting logcat and if it's a bug please fix it. ( compile 'me.leolin:ShortcutBadger:1.1.3' ) 

```
E/ShortcutBadger: <init> [class android.content.Context]
                  java.lang.NoSuchMethodException: <init> [class android.content.Context]
                      at java.lang.Class.getConstructor(Class.java:531)
                      at java.lang.Class.getConstructor(Class.java:495)
                      at me.leolin.shortcutbadger.ShortcutBadger.getShortcutBadger(ShortcutBadger.java:74)
                      at me.leolin.shortcutbadger.ShortcutBadger.with(ShortcutBadger.java:42)
                      at com.unitedinternet.portal.ui.BaseActivity.resetShortcutBadgeCount(BaseActivity.java:105)
                      at com.unitedinternet.portal.ui.BaseActivity.onResume(BaseActivity.java:209)
                      at com.unitedinternet.portal.ui.HostActivity.onResume(HostActivity.java:432)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1271)
                      at android.app.Activity.performResume(Activity.java:6621)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4033)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
                      at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6837)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by leolin310148** [comment]
The construct has been changed in new version, this should not happened anymore.
