### ISSUE TITLE
unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

### ISSUE THREAD

**Issue by estysherman** [leolin310148/ShortcutBadger#90]
i am trying to run this project.
but i get this error:
E/ShortcutBadger: Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }

i have no idea what the problem.
anyone can help me?
thanks.

**Comment by saladthieves** [comment]
@estysherman I seem to also be having the same problem.

**Comment by gitzgq** [comment]
Me too
Did you solve it?

**Comment by EranMan** [comment]
Me too 
anyOne know that?

**Comment by valueNow** [comment]
How much is your SDK version?Some custom lancher custom badge intent is not the same as the project's intent，i think @estysherman

**Comment by baiju-emedsim** [comment]
Me too 
anyOne know that?

**Comment by msajjadawan** [comment]
I resolve this problem  by using code directly in my application and making a change in executeBadge method of DefaultBadger class
=======================       
//added 
context.sendBroadcast(intent);

// commented
//        if(BroadcastHelper.canResolveBroadcast(context, intent)) {
//            context.sendBroadcast(intent);
//        } else {
//            throw new ShortcutBadgeException("unable to resolve intent: " + intent.toString());
//        }
=================

**Comment by hielkehoeve** [comment]
This obviously won't fix the issue as nothing is listening for this Intent. Not getting this error makes it even worse as developers think it works fine...

**Comment by leoleohan** [comment]
The same issue,Samsung SM-N9009, v1.1.8.
Finally I found a solution in StackOverFlow.

**Comment by leoleohan** [comment]
@varunrramani 
I can't find the link now, but I used the code in my test project. Click the url below:
[LauncherBadge/app/src/main/java/com/leihan/launcherbadge/MainActivity.java](url)
Better run my test App.

**Comment by sfyc23** [comment]
@leoleohan  This address is 404.

**Comment by leoleohan** [comment]
@sfyc23 paste this address in your browser.
https://github.com/leoleohan/LauncherBadge

**Comment by MarshallZhug** [comment]
将 DefaultBadger 中的 executeBadge(Context context, ComponentName componentName, int badgeCount)修改： 
public void executeBadge(Context context, ComponentName componentName, int badgeCount) throws ShortcutBadgeException {
        Intent intent = new Intent(INTENT_ACTION);
        intent.putExtra(INTENT_EXTRA_BADGE_COUNT, badgeCount);
        intent.putExtra(INTENT_EXTRA_PACKAGENAME, componentName.getPackageName());
        intent.putExtra(INTENT_EXTRA_ACTIVITY_NAME, componentName.getClassName());
//        if(BroadcastHelper.canResolveBroadcast(context, intent)) {
//            context.sendBroadcast(intent);
//        } else {
//            throw new ShortcutBadgeException("unable to resolve intent: " + intent.toString());
//        }
        context.sendBroadcast(intent);
    }
也就是将此方法中的if判断注释掉，  
Ps:  也就是将 msajjadawan 提供的解决方法更直白的表现出来了

**Comment by litingjun2015** [comment]
我用 MI 2
Android: 5.0.2 LRX22G 也是报：

```
11-02 16:10:46.706 10986-11248/? E/ShortcutBadger: Unable to execute badge
                                                   me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
                                                       at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:78)
                                                       at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:53)
                                                       at com.bizappv3.UMCModule.startActivityFromJSGetResult(UMCModule.java:93)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.APPLICATION_MESSAGE_UPDATE (has extras) }
                                                       at me.leolin.shortcutbadger.impl.XiaomiHomeBadger.executeBadge(XiaomiHomeBadger.java:41)
                                                       at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:76)
                                                       at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:53) 
                                                       at com.bizappv3.UMCModule.startActivityFromJSGetResult(UMCModule.java:93) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318) 
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                       at java.lang.Thread.run(Thread.java:818) 
```

SumSung SM-C5000 is ok.

**Comment by hfarhanahmed** [comment]
Getting the same error on Nexus 5

**Comment by ranihorev** [comment]
It happens to me just on Apex Launcher on LG G3. It works when switch back to default launcher

**Comment by litingjun2015** [comment]
@leolin310148 , this issue is closed with which solution?

**Comment by hielkehoeve** [comment]
None. It looks to me like library is broken and won't be fixed.

**Comment by firelion0725** [comment]
我的LG设备也是false 显示同样的异常。
My LG phone also show "false" It's same error. I don't know what I should do.

**Comment by georgi8706** [comment]
Has anyone fixed this problem? I have the same error on LG G6 (API26).

**Comment by krishnadas89** [comment]
I am facing the same issue.. 
<img width="1497" alt="screenshot 2018-11-22 at 1 37 27 pm" src="https://user-images.githubusercontent.com/7599778/48889455-fedb0000-ee5b-11e8-8649-32faf34a07f9.png">
How can this be closed without any proper solution provided.

**Comment by glebkravchenko** [comment]
same problem, how to fix this?

**Comment by naveedahmad99** [comment]
1.1.22 same issue

**Comment by poonam-yadav100691** [comment]
Same issues please help

**Comment by balajiks-dev** [comment]
This issue is not yet resolved. Hence, reopen this issue.
