### ISSUE TITLE
NullPointerException when initBadger

### ISSUE THREAD

**Issue by hendrawd** [leolin310148/ShortcutBadger#98]
There is a NullPointerException when i set the badge count to 0 on activity's onResume

Here is the stack trace:        
```
Caused by java.lang.NullPointerException
        at me.leolin.shortcutbadger.ShortcutBadger.initBadger(ShortcutBadger.java:100)
        at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:73)
        at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:58)
        at myApp.AppUtil.resetNewPhotoCounter(AppUtil.java:161)
        at myApp.activity.MainActivity.onResume(MainActivity.java:452)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
        at android.app.Activity.performResume(Activity.java:5082)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2573)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
        at android.app.ActivityThread.access$600(ActivityThread.java:133)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4810)
        at java.lang.reflect.Method.invokeNative(Method.java)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
        at dalvik.system.NativeStart.main(NativeStart.java)
```

and inside AppUtil.resetNewPhotoCounter is this line of code 
`ShortcutBadger.applyCount(context.getApplicationContext(), 0);`

Other informations:
Date: 2016-07-10T13:42:46Z
OS Version: 4.1.2
Device: Andromax-c
RAM Free: 15%
Disk Free: 39.9%

**Comment by MajeurAndroid** [comment]
If you run the latest version, line 100 points to:

context.getPackageManager().resolveActivity(intent, MATCH_DEFAULT_ONLY);

context cannot be null because its reference is used above.
Same for getPackageManager() method.

The NPE appends probably at line 101 when trying to read packageName field. It means that no launcher is set as default, so the MATCH_DEFAULT_ONLY makes the result of the query to package manager null. A null check is required.

Also, you can pass a regular context to applyCount method, instead of application level context.

**Comment by hendrawd** [comment]
the current version of my ShortcutBadger on line 100 is 
`sComponentName = context.getPackageManager().getLaunchIntentForPackage(context.getPackageName()).getComponent();`

**Comment by hendrawd** [comment]
@MajeurAndroid I suppose the problem is because of null application context. If i change the context to activity or service and make sure it not null, will it save the problem?

**Comment by hendrawd** [comment]
Ok, what i have done here are:
- Update to version 1.1.6
- Change context from application context to local context(Service, Activity, etc)
- Check if context is null before call ShortcutBadger.applyCount
I hope this will solve the null pointer exception problem, since i can't check and replicate the bug directly, because it happened on one of my client phone that i don't have access to.
